// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (workspace_id, name, color) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING RETURNING id, workspace_id, name, color, created_at
`

type CreateLabelParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.WorkspaceID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (workspace_id, name, email, password_hash, role)
VALUES ($1, $2, $5::text, $3, $4) RETURNING id, workspace_id, name, email, password_hash, role, active, created_at, updated_at
`

type CreateUserParams struct {
	WorkspaceID  int64  `json:"workspace_id"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Email        string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.WorkspaceID,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name) VALUES ($1) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.workspace_id, u.name, u.email, u.role, u.active, u.created_at, u.updated_at,
       w.name AS workspace_name, w.app_name, w.logo IS NOT NULL AS has_logo
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN workspaces w ON w.id = u.workspace_id
WHERE s.token_hash = $1 AND s.expires_at > now() AND u.active = true
`

type GetSessionUserRow struct {
	ID            int64              `json:"id"`
	WorkspaceID   int64              `json:"workspace_id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	Role          string             `json:"role"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	WorkspaceName string             `json:"workspace_name"`
	AppName       string             `json:"app_name"`
	HasLogo       bool               `json:"has_logo"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceName,
		&i.AppName,
		&i.HasLogo,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, workspace_id, name, email, password_hash, role, active, created_at, updated_at FROM users WHERE lower(email) = lower($1) AND active = true LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceLabel = `-- name: GetWorkspaceLabel :one
SELECT id, workspace_id, name, color, created_at FROM labels WHERE id = $1 AND workspace_id = $2
`

type GetWorkspaceLabelParams struct {
	ID          int64 `json:"id"`
	WorkspaceID int64 `json:"workspace_id"`
}

func (q *Queries) GetWorkspaceLabel(ctx context.Context, arg GetWorkspaceLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, getWorkspaceLabel, arg.ID, arg.WorkspaceID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceUser = `-- name: GetWorkspaceUser :one
SELECT id, workspace_id, name, email, password_hash, role, active, created_at, updated_at FROM users WHERE id = $1 AND workspace_id = $2 AND active = true
`

type GetWorkspaceUserParams struct {
	ID          int64 `json:"id"`
	WorkspaceID int64 `json:"workspace_id"`
}

func (q *Queries) GetWorkspaceUser(ctx context.Context, arg GetWorkspaceUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getWorkspaceUser, arg.ID, arg.WorkspaceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, workspace_id, name, color, created_at FROM labels WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, workspaceID int64) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, workspace_id, name, email, role, active, created_at, updated_at
FROM users WHERE workspace_id = $1 ORDER BY name
`

type ListUsersRow struct {
	ID          int64              `json:"id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, workspaceID int64) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOnboarding = `-- name: LockOnboarding :exec
SELECT pg_advisory_xact_lock(1984001)
`

func (q *Queries) LockOnboarding(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOnboarding)
	return err
}

const workspaceCount = `-- name: WorkspaceCount :one
SELECT count(*) FROM workspaces
`

func (q *Queries) WorkspaceCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, workspaceCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
