// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const calendarRange = `-- name: CalendarRange :many
SELECT i.id, i.number, i.title, p.key AS project_key, i.start_date, i.due_date,
       NULL::date AS target_date, 'issue'::text AS item_kind
FROM issues i JOIN projects p ON p.id = i.project_id
WHERE p.workspace_id = $1
 AND ($2::text = '' OR p.key = $2)
 AND ((i.start_date >= $3::date AND i.start_date < $4::date)
   OR (i.due_date >= $3::date AND i.due_date < $4::date))
UNION ALL
SELECT r.id, 0, coalesce(nullif(r.name, ''), r.version), p.key, NULL::date, NULL::date,
       r.target_date, 'release'::text
FROM releases r JOIN projects p ON p.id = r.project_id
WHERE p.workspace_id = $1
 AND ($2::text = '' OR p.key = $2)
 AND r.target_date >= $3::date AND r.target_date < $4::date
ORDER BY target_date NULLS LAST, due_date NULLS LAST, start_date NULLS LAST
LIMIT 1000
`

type CalendarRangeParams struct {
	WorkspaceID int64       `json:"workspace_id"`
	ProjectKey  string      `json:"project_key"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
}

type CalendarRangeRow struct {
	ID         int64       `json:"id"`
	Number     int32       `json:"number"`
	Title      string      `json:"title"`
	ProjectKey string      `json:"project_key"`
	StartDate  pgtype.Date `json:"start_date"`
	DueDate    pgtype.Date `json:"due_date"`
	TargetDate pgtype.Date `json:"target_date"`
	ItemKind   string      `json:"item_kind"`
}

func (q *Queries) CalendarRange(ctx context.Context, arg CalendarRangeParams) ([]CalendarRangeRow, error) {
	rows, err := q.db.Query(ctx, calendarRange,
		arg.WorkspaceID,
		arg.ProjectKey,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarRangeRow{}
	for rows.Next() {
		var i CalendarRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Title,
			&i.ProjectKey,
			&i.StartDate,
			&i.DueDate,
			&i.TargetDate,
			&i.ItemKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
