// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentRelease = `-- name: CurrentRelease :one
SELECT r.id, r.version, r.name, r.target_date, p.key AS project_key,
       count(i.id)::bigint AS issue_count,
       count(i.id) FILTER (WHERE i.status = 'done')::bigint AS done_count
FROM releases r JOIN projects p ON p.id = r.project_id LEFT JOIN issues i ON i.release_id = r.id
WHERE p.workspace_id = $1 AND r.status = 'active'
GROUP BY r.id, p.key ORDER BY r.target_date NULLS LAST LIMIT 1
`

type CurrentReleaseRow struct {
	ID         int64       `json:"id"`
	Version    string      `json:"version"`
	Name       string      `json:"name"`
	TargetDate pgtype.Date `json:"target_date"`
	ProjectKey string      `json:"project_key"`
	IssueCount int64       `json:"issue_count"`
	DoneCount  int64       `json:"done_count"`
}

func (q *Queries) CurrentRelease(ctx context.Context, workspaceID int64) (CurrentReleaseRow, error) {
	row := q.db.QueryRow(ctx, currentRelease, workspaceID)
	var i CurrentReleaseRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.TargetDate,
		&i.ProjectKey,
		&i.IssueCount,
		&i.DoneCount,
	)
	return i, err
}

const dashboardStats = `-- name: DashboardStats :one
SELECT
  count(i.id) FILTER (WHERE i.status NOT IN ('done', 'canceled'))::bigint AS open_issues,
  count(i.id) FILTER (WHERE i.status = 'done')::bigint AS completed_issues,
  count(i.id) FILTER (WHERE i.type = 'bug' AND i.status NOT IN ('done', 'canceled'))::bigint AS open_bugs,
  coalesce((SELECT sum(CASE WHEN te.ended_at IS NULL THEN extract(epoch FROM (now() - te.started_at))::bigint ELSE te.duration_seconds::bigint END)
            FROM time_entries te JOIN users u ON u.id = te.user_id WHERE u.workspace_id = $1), 0)::bigint AS tracked_seconds
FROM issues i JOIN projects p ON p.id = i.project_id WHERE p.workspace_id = $1
`

type DashboardStatsRow struct {
	OpenIssues      int64 `json:"open_issues"`
	CompletedIssues int64 `json:"completed_issues"`
	OpenBugs        int64 `json:"open_bugs"`
	TrackedSeconds  int64 `json:"tracked_seconds"`
}

func (q *Queries) DashboardStats(ctx context.Context, workspaceID int64) (DashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardStats, workspaceID)
	var i DashboardStatsRow
	err := row.Scan(
		&i.OpenIssues,
		&i.CompletedIssues,
		&i.OpenBugs,
		&i.TrackedSeconds,
	)
	return i, err
}

const recentIssues = `-- name: RecentIssues :many
SELECT i.id, i.number, i.title, i.status, i.type, i.priority, i.updated_at, p.key AS project_key
FROM issues i JOIN projects p ON p.id = i.project_id
WHERE p.workspace_id = $1 ORDER BY i.updated_at DESC LIMIT $2
`

type RecentIssuesParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Limit       int32 `json:"limit"`
}

type RecentIssuesRow struct {
	ID         int64              `json:"id"`
	Number     int32              `json:"number"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	Type       string             `json:"type"`
	Priority   string             `json:"priority"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ProjectKey string             `json:"project_key"`
}

func (q *Queries) RecentIssues(ctx context.Context, arg RecentIssuesParams) ([]RecentIssuesRow, error) {
	rows, err := q.db.Query(ctx, recentIssues, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentIssuesRow{}
	for rows.Next() {
		var i RecentIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Type,
			&i.Priority,
			&i.UpdatedAt,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
