// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGitHubDelivery = `-- name: ClaimGitHubDelivery :execrows
INSERT INTO github_deliveries (delivery_id,event) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type ClaimGitHubDeliveryParams struct {
	DeliveryID string `json:"delivery_id"`
	Event      string `json:"event"`
}

func (q *Queries) ClaimGitHubDelivery(ctx context.Context, arg ClaimGitHubDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimGitHubDelivery, arg.DeliveryID, arg.Event)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitHubInstallation = `-- name: DeleteGitHubInstallation :exec
DELETE FROM github_installations WHERE installation_id=$1
`

func (q *Queries) DeleteGitHubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubInstallation, installationID)
	return err
}

const deleteOldGitHubDeliveries = `-- name: DeleteOldGitHubDeliveries :exec
DELETE FROM github_deliveries WHERE processed_at < now() - interval '30 days'
`

func (q *Queries) DeleteOldGitHubDeliveries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldGitHubDeliveries)
	return err
}

const findIssueReference = `-- name: FindIssueReference :one
SELECT i.id, i.project_id, i.number, i.title, i.description, i.type, i.status, i.priority, i.assignee_id, i.reporter_id, i.estimated_minutes, i.start_date, i.due_date, i.release_id, i.created_at, i.updated_at, i.closed_at, i.sprint_id FROM issues i JOIN projects p ON p.id = i.project_id
WHERE p.workspace_id = $1 AND p.key = upper($2) AND i.number = $3
`

type FindIssueReferenceParams struct {
	WorkspaceID int64       `json:"workspace_id"`
	Upper       interface{} `json:"upper"`
	Number      int32       `json:"number"`
}

func (q *Queries) FindIssueReference(ctx context.Context, arg FindIssueReferenceParams) (Issue, error) {
	row := q.db.QueryRow(ctx, findIssueReference, arg.WorkspaceID, arg.Upper, arg.Number)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EstimatedMinutes,
		&i.StartDate,
		&i.DueDate,
		&i.ReleaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SprintID,
	)
	return i, err
}

const getGitHubRepositoryByExternalID = `-- name: GetGitHubRepositoryByExternalID :one
SELECT gr.id, gr.project_id, gr.installation_id, gr.repository_id, gr.owner, gr.name, gr.full_name, gr.default_branch, gr.created_at, gr.updated_at, p.workspace_id, p.key AS project_key
FROM github_repositories gr JOIN projects p ON p.id = gr.project_id
WHERE gr.repository_id = $1
`

type GetGitHubRepositoryByExternalIDRow struct {
	ID             int64              `json:"id"`
	ProjectID      int64              `json:"project_id"`
	InstallationID int64              `json:"installation_id"`
	RepositoryID   int64              `json:"repository_id"`
	Owner          string             `json:"owner"`
	Name           string             `json:"name"`
	FullName       string             `json:"full_name"`
	DefaultBranch  string             `json:"default_branch"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID    int64              `json:"workspace_id"`
	ProjectKey     string             `json:"project_key"`
}

func (q *Queries) GetGitHubRepositoryByExternalID(ctx context.Context, repositoryID int64) (GetGitHubRepositoryByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getGitHubRepositoryByExternalID, repositoryID)
	var i GetGitHubRepositoryByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstallationID,
		&i.RepositoryID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.ProjectKey,
	)
	return i, err
}

const getGitHubRepositoryByProject = `-- name: GetGitHubRepositoryByProject :one
SELECT gr.id, gr.project_id, gr.installation_id, gr.repository_id, gr.owner, gr.name, gr.full_name, gr.default_branch, gr.created_at, gr.updated_at, gi.installation_id AS github_installation_id
FROM github_repositories gr JOIN github_installations gi ON gi.id = gr.installation_id
WHERE gr.project_id = $1
`

type GetGitHubRepositoryByProjectRow struct {
	ID                   int64              `json:"id"`
	ProjectID            int64              `json:"project_id"`
	InstallationID       int64              `json:"installation_id"`
	RepositoryID         int64              `json:"repository_id"`
	Owner                string             `json:"owner"`
	Name                 string             `json:"name"`
	FullName             string             `json:"full_name"`
	DefaultBranch        string             `json:"default_branch"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	GithubInstallationID int64              `json:"github_installation_id"`
}

func (q *Queries) GetGitHubRepositoryByProject(ctx context.Context, projectID int64) (GetGitHubRepositoryByProjectRow, error) {
	row := q.db.QueryRow(ctx, getGitHubRepositoryByProject, projectID)
	var i GetGitHubRepositoryByProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstallationID,
		&i.RepositoryID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
	)
	return i, err
}

const linkGitHubRepository = `-- name: LinkGitHubRepository :one
INSERT INTO github_repositories (project_id, installation_id, repository_id, owner, name, full_name, default_branch)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id) DO UPDATE SET installation_id = excluded.installation_id, repository_id = excluded.repository_id,
owner = excluded.owner, name = excluded.name, full_name = excluded.full_name, default_branch = excluded.default_branch, updated_at = now()
RETURNING id, project_id, installation_id, repository_id, owner, name, full_name, default_branch, created_at, updated_at
`

type LinkGitHubRepositoryParams struct {
	ProjectID      int64  `json:"project_id"`
	InstallationID int64  `json:"installation_id"`
	RepositoryID   int64  `json:"repository_id"`
	Owner          string `json:"owner"`
	Name           string `json:"name"`
	FullName       string `json:"full_name"`
	DefaultBranch  string `json:"default_branch"`
}

func (q *Queries) LinkGitHubRepository(ctx context.Context, arg LinkGitHubRepositoryParams) (GithubRepository, error) {
	row := q.db.QueryRow(ctx, linkGitHubRepository,
		arg.ProjectID,
		arg.InstallationID,
		arg.RepositoryID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.DefaultBranch,
	)
	var i GithubRepository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstallationID,
		&i.RepositoryID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueCommits = `-- name: ListIssueCommits :many
SELECT id, repository_id, issue_id, sha, message, url, author_name, authored_at, created_at FROM github_commits WHERE issue_id = $1 ORDER BY authored_at DESC LIMIT 50
`

func (q *Queries) ListIssueCommits(ctx context.Context, issueID int64) ([]GithubCommit, error) {
	rows, err := q.db.Query(ctx, listIssueCommits, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubCommit{}
	for rows.Next() {
		var i GithubCommit
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.IssueID,
			&i.Sha,
			&i.Message,
			&i.Url,
			&i.AuthorName,
			&i.AuthoredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuePullRequests = `-- name: ListIssuePullRequests :many
SELECT id, repository_id, issue_id, number, title, state, merged, url, updated_at, created_at FROM github_pull_requests WHERE issue_id = $1 ORDER BY updated_at DESC LIMIT 50
`

func (q *Queries) ListIssuePullRequests(ctx context.Context, issueID int64) ([]GithubPullRequest, error) {
	rows, err := q.db.Query(ctx, listIssuePullRequests, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubPullRequest{}
	for rows.Next() {
		var i GithubPullRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.IssueID,
			&i.Number,
			&i.Title,
			&i.State,
			&i.Merged,
			&i.Url,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseGitHubCounts = `-- name: ReleaseGitHubCounts :one
SELECT
 (SELECT count(DISTINCT pr.number)::bigint FROM github_pull_requests pr JOIN issues i ON i.id=pr.issue_id WHERE i.release_id=$1) AS pull_requests,
 (SELECT count(DISTINCT c.sha)::bigint FROM github_commits c JOIN issues i ON i.id=c.issue_id WHERE i.release_id=$1) AS commits
`

type ReleaseGitHubCountsRow struct {
	PullRequests int64 `json:"pull_requests"`
	Commits      int64 `json:"commits"`
}

func (q *Queries) ReleaseGitHubCounts(ctx context.Context, releaseID pgtype.Int8) (ReleaseGitHubCountsRow, error) {
	row := q.db.QueryRow(ctx, releaseGitHubCounts, releaseID)
	var i ReleaseGitHubCountsRow
	err := row.Scan(&i.PullRequests, &i.Commits)
	return i, err
}

const updateGitHubReleaseFromWebhook = `-- name: UpdateGitHubReleaseFromWebhook :exec
UPDATE releases SET github_url=$2, status=$3, updated_at=now()
WHERE github_release_id=$1 AND project_id=$4
`

type UpdateGitHubReleaseFromWebhookParams struct {
	GithubReleaseID pgtype.Int8 `json:"github_release_id"`
	GithubUrl       pgtype.Text `json:"github_url"`
	Status          string      `json:"status"`
	ProjectID       int64       `json:"project_id"`
}

func (q *Queries) UpdateGitHubReleaseFromWebhook(ctx context.Context, arg UpdateGitHubReleaseFromWebhookParams) error {
	_, err := q.db.Exec(ctx, updateGitHubReleaseFromWebhook,
		arg.GithubReleaseID,
		arg.GithubUrl,
		arg.Status,
		arg.ProjectID,
	)
	return err
}

const upsertGitHubCommit = `-- name: UpsertGitHubCommit :execrows
INSERT INTO github_commits (repository_id, issue_id, sha, message, url, author_name, authored_at)
VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT DO NOTHING
`

type UpsertGitHubCommitParams struct {
	RepositoryID int64              `json:"repository_id"`
	IssueID      int64              `json:"issue_id"`
	Sha          string             `json:"sha"`
	Message      string             `json:"message"`
	Url          string             `json:"url"`
	AuthorName   string             `json:"author_name"`
	AuthoredAt   pgtype.Timestamptz `json:"authored_at"`
}

func (q *Queries) UpsertGitHubCommit(ctx context.Context, arg UpsertGitHubCommitParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertGitHubCommit,
		arg.RepositoryID,
		arg.IssueID,
		arg.Sha,
		arg.Message,
		arg.Url,
		arg.AuthorName,
		arg.AuthoredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGitHubInstallation = `-- name: UpsertGitHubInstallation :one
INSERT INTO github_installations (workspace_id, installation_id, account_login, account_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (installation_id) DO UPDATE SET account_login = excluded.account_login, account_id = excluded.account_id, updated_at = now()
RETURNING id, workspace_id, installation_id, account_login, account_id, created_at, updated_at
`

type UpsertGitHubInstallationParams struct {
	WorkspaceID    int64       `json:"workspace_id"`
	InstallationID int64       `json:"installation_id"`
	AccountLogin   string      `json:"account_login"`
	AccountID      pgtype.Int8 `json:"account_id"`
}

func (q *Queries) UpsertGitHubInstallation(ctx context.Context, arg UpsertGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGitHubInstallation,
		arg.WorkspaceID,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountID,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubPullRequest = `-- name: UpsertGitHubPullRequest :execrows
INSERT INTO github_pull_requests (repository_id, issue_id, number, title, state, merged, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repository_id, number, issue_id) DO UPDATE SET title = excluded.title, state = excluded.state,
merged = excluded.merged, url = excluded.url, updated_at = now()
WHERE (github_pull_requests.title,github_pull_requests.state,github_pull_requests.merged,github_pull_requests.url)
IS DISTINCT FROM (excluded.title,excluded.state,excluded.merged,excluded.url)
`

type UpsertGitHubPullRequestParams struct {
	RepositoryID int64  `json:"repository_id"`
	IssueID      int64  `json:"issue_id"`
	Number       int32  `json:"number"`
	Title        string `json:"title"`
	State        string `json:"state"`
	Merged       bool   `json:"merged"`
	Url          string `json:"url"`
}

func (q *Queries) UpsertGitHubPullRequest(ctx context.Context, arg UpsertGitHubPullRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertGitHubPullRequest,
		arg.RepositoryID,
		arg.IssueID,
		arg.Number,
		arg.Title,
		arg.State,
		arg.Merged,
		arg.Url,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
