// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sprints.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTodoToSprint = `-- name: AssignTodoToSprint :many
UPDATE issues
SET sprint_id = $1, updated_at = now()
WHERE project_id = $2
  AND sprint_id IS NULL
  AND status = 'todo'
RETURNING id
`

type AssignTodoToSprintParams struct {
	SprintID  pgtype.Int8 `json:"sprint_id"`
	ProjectID int64       `json:"project_id"`
}

func (q *Queries) AssignTodoToSprint(ctx context.Context, arg AssignTodoToSprintParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, assignTodoToSprint, arg.SprintID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (project_id, name, start_date, end_date)
VALUES ($1, $2, $3, $4) RETURNING id, project_id, name, start_date, end_date, created_at, started_at
`

type CreateSprintParams struct {
	ProjectID int64       `json:"project_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.ProjectID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.StartedAt,
	)
	return i, err
}

const getProjectSprint = `-- name: GetProjectSprint :one
SELECT id, project_id, name, start_date, end_date, created_at, started_at FROM sprints WHERE id = $1 AND project_id = $2
`

type GetProjectSprintParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) GetProjectSprint(ctx context.Context, arg GetProjectSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, getProjectSprint, arg.ID, arg.ProjectID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.StartedAt,
	)
	return i, err
}

const listProjectSprints = `-- name: ListProjectSprints :many
SELECT id, project_id, name, start_date, end_date, created_at, started_at FROM sprints WHERE project_id = $1 ORDER BY start_date DESC, id DESC
`

func (q *Queries) ListProjectSprints(ctx context.Context, projectID int64) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listProjectSprints, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSprintStarted = `-- name: MarkSprintStarted :exec
UPDATE sprints
SET started_at = now()
WHERE id = $1 AND project_id = $2 AND started_at IS NULL
`

type MarkSprintStartedParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) MarkSprintStarted(ctx context.Context, arg MarkSprintStartedParams) error {
	_, err := q.db.Exec(ctx, markSprintStarted, arg.ID, arg.ProjectID)
	return err
}

const prepareSprintIssues = `-- name: PrepareSprintIssues :exec
UPDATE issues
SET status = 'backlog', updated_at = now()
WHERE project_id = $1
  AND sprint_id IS NULL
  AND status NOT IN ('done', 'canceled')
`

func (q *Queries) PrepareSprintIssues(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, prepareSprintIssues, projectID)
	return err
}

const setIssueSprint = `-- name: SetIssueSprint :exec
UPDATE issues SET sprint_id = $2, updated_at = now() WHERE id = $1
`

type SetIssueSprintParams struct {
	ID       int64       `json:"id"`
	SprintID pgtype.Int8 `json:"sprint_id"`
}

func (q *Queries) SetIssueSprint(ctx context.Context, arg SetIssueSprintParams) error {
	_, err := q.db.Exec(ctx, setIssueSprint, arg.ID, arg.SprintID)
	return err
}
